name: "UbuntuDemo"
on: [ "push", "pull_request" ]

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: ayuge
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: RootAyuge
          MYSQL_DATABASE: demo
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        pip install -U poetry pytest coverage
        poetry install -E "all"
        source "$(poetry env info --path)/bin/activate"
        coverage run -m pytest tests/test_items.py tests/test_formatdata.py tests/test_sqlformat.py tests/test_commands/test_commands_startproject.py tests/test_commands/test_commands_version.py tests/test_common/test_common_multiplexing.py tests/test_common/test_common_typevars.py tests/test_common/test_common_utils.py tests/test_extras/test_extras_cvnpil.py -k "not test_get_remote_kvs and not test_fetch_remote_conf and not test_normal_to_stamp"
        coverage combine
        coverage report

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
