name: "UbuntuDemo"
on: [ "push", "pull_request" ]

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: ayuge
          MYSQL_PASSWORD: test
          MYSQL_ROOT_PASSWORD: RootAyuge
          MYSQL_DATABASE: demo
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Run tests
      run: |
        pip install -U poetry tox
        tox

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
